### ISSUE TITLE
http服务器图片不显示，iOS工程info.plist已配置ATS

### ISSUE THREAD

**Issue by rhwish** [cainvan/react-native-zkbanner#1]

**Comment by cainvan** [comment]
http://www.10086.cn/cmpop/images/index/ad1/201607/201607291033143254wN.jpg
用以上图片尝试了，配置ATS后能够正常显示。

**Comment by rhwish** [comment]
@cainvan 我测试了下也可以了，原因可能在url地址中不能包含中文，因为在昨天测试时地址中有中文。非常感谢您的轮子以及回复~~
